### PR TITLE
Support slevomat/coding-standard 8.x + make PHP 8.1 default

### PR DESCRIPTION
**Pull request by jonnyeom**
These are big changes. It is BC breaking and should be a new major release.
- Up selvomat/coding-standard to 8.x
- Up phpcs version to 3.7.x
- Remove php 7.1, 7.2, 7.3 support.
- Upgrade fixtures with current methodologies of doctrine/coding-standard (for future maintainability)

### CODE REVIEW

**Comment by colinodell** [comment]
Feel free to remove the `Generic.Formatting.MultipleStatementAlignment` sniff too, if you'd like.  I kind of hate it now :P Your call though!

**Comment by jonnyeom** [comment]
@colinodell 
This change will make this fail on php 7.4 I realized.

What do you think of only supporting php 8+?

**Comment by colinodell** [comment]
I think that's fine since 7.4 is EOL and anyone who really needs 7.4 support can still use existing versions of this standard.

**Comment by jonnyeom** [comment]
Remove the Generic.Formatting.MultipleStatementAlignment. I dont mind but it does cause unnecessary changes sometimes


I think this is a good start.

At this point, we havent added much php 8 specific rules yet, I think we can add several rules but that can be discussed after an initial slevomat 8.x support release.

Please feel free to critique / suggest

**Comment by jonnyeom** [comment]
Perhaps it would be easier if we make a 4.0.x branch?

**Pull request merged**
